## Problem1

In [1]:
import numpy as np

In [2]:
def exp_dist(x, tao):
    pdf = (1/tao)*np.exp(-x/tao)
    return pdf

In [3]:
taos = [1, 2]
pis = [0.5, 0.5]
Xs = [0, 2, 4]
joint_probs = np.zeros(
    (len(pis), len(Xs))
)
sum_joint_probs = np.zeros(
    len(Xs)
)

In [4]:
for i, x in enumerate(Xs):
    sum_joint_prob = 0
    for j, tao in enumerate(taos):
        joint_prob = pis[j] * exp_dist(Xs[i], taos[j])
        joint_probs[j][i] = joint_prob
        sum_joint_prob += joint_prob
    sum_joint_probs[i] = sum_joint_prob

In [5]:
deltas = joint_probs / sum_joint_probs
print("The answer of problem 1-(c) is")
print(
    np.concatenate(
        [joint_probs, sum_joint_probs.reshape(-1, 3), deltas],
        axis = 0
    )
)

The answer of problem 1-(c) is
[[0.5        0.06766764 0.00915782]
 [0.25       0.09196986 0.03383382]
 [0.75       0.1596375  0.04299164]
 [0.66666667 0.42388312 0.21301396]
 [0.33333333 0.57611688 0.78698604]]


## Problem 1(d)

In [6]:
deltas_j = np.sum(deltas, axis = 1)
delta_sum_i_j = np.sum(deltas)
pis_iter_1 = deltas_j / delta_sum_i_j
taos_iter_1 = np.sum(deltas * Xs, axis = 1) / deltas_j

In [7]:
print("Iteration 1: M steps")
for i in range(2):
        print(f"tau_{i+1}: {round(taos_iter_1[i], 5)}, pi_{i+1}: {round(pis_iter_1[i], 5)}")

Iteration 1: M steps
tau_1: 1.30398, pi_1: 0.43452
tau_2: 2.53483, pi_2: 0.56548


## Problem2 (a)

In [8]:
from sklearn.decomposition import PCA

In [9]:
X = np.array([
    [1, 2, 3], 
    [4, 8, 5], 
    [3, 12, 9], 
    [1, 8, 5], 
    [5, 14, 2],
    [7, 4, 1], 
    [9, 8, 9],
    [3, 8, 1],
    [11, 5, 6],
    [10, 11, 7]
])
pca = PCA()
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [10]:
print(f"Principle axes:")
for i in range(X.shape[1]):
    print(f"{i+1}-th principle axes: {pca.components_[i]}")

Principle axes:
1-th principle axes: [-0.6165947  -0.58881629 -0.52259579]
2-th principle axes: [ 0.67817891 -0.73439013  0.02728563]
3-th principle axes: [ 0.39985541  0.33758926 -0.85214385]


## Problem 2(b)

In [11]:
X_pca = pca.fit_transform(X)
print(f"Principle components:")
for i in range(X.shape[0]):
    print(f"Sample {i+1}, principle components: {X_pca[i]}")

Principle components:
Sample 1, principle components: [ 7.18658682  1.37323947 -2.25104047]
Sample 2, principle components: [ 0.75871342 -0.94399334 -0.73022635]
Sample 3, principle components: [-3.07034019 -4.45059025 -3.1883001 ]
Sample 4, principle components: [ 2.60849751 -2.97853006 -1.92979259]
Sample 5, principle components: [-1.82299166 -4.75401212  4.25159619]
Sample 6, principle components: [3.35457763 3.91896138 2.52755823]
Sample 7, principle components: [-4.41464321  2.55604371 -2.13952468]
Sample 8, principle components: [ 3.46569126 -1.73131477  2.27849363]
Sample 9, principle components: [-2.31359638  6.03371503  0.2038499 ]
Sample 10, principle components: [-5.75249521  0.97648096  0.97738622]


## Problem 2(c)

In [12]:
PCA_dim2 = PCA(n_components=2)
X_pca_dim2 = PCA_dim2.fit_transform(X)
X_reconstruct = PCA_dim2.inverse_transform(X_pca_dim2)

In [13]:
print("Reconstruction dataset")
print(X_reconstruct)

Reconstruction dataset
[[ 1.90009072  2.75992709  1.08178971]
 [ 4.29198496  8.24651657  4.37774211]
 [ 4.27485905 13.07633588  6.28310968]
 [ 1.77163801  8.65147726  3.35553912]
 [ 3.29997625 12.56470677  5.62297154]
 [ 5.98934216  3.14672348  3.1538432 ]
 [ 9.85550052  8.72228056  7.17681721]
 [ 2.08893199  7.23080501  2.94160433]
 [10.91848951  4.93118246  6.17370944]
 [ 9.60918683 10.6700449   7.83287366]]


In [14]:
average_squared_error = np.mean(
    np.linalg.norm(X - X_reconstruct, axis = 1) ** 2
)
print(f"Average reconstruction error is {round(average_squared_error, 5)}")

Average reconstruction error is 5.47203
